### ISSUE TITLE
Rename repo to pyxdf

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/pyxdf#55]
The package name is pyxdf, and if you google for pyxdf you won't find this repo at all (at least not on the first page). Therefore, I'd like to change the repo name to pyxdf, which would also be much more consistent.

**Comment by cboulay** [comment]
We have xdf-Matlab, liblsl-Python, liblsl-Matlab, etc. I don't think this repo should diverge from all of the other repos in the ecosystem just so the repo name matches the name of the Python package.

And, at least for me, if I google pyxdf, the pypi page is the first hit and the conda page is the second hit. IMO that's correct because pyxdf is the name of the python package. Also, we want casual users getting the package from pypi, not from github.

You're more than welcome to put more keywords in the repo description.

**Comment by cbrnr** [comment]
You're right, the first search result is the PyPI site. However, the second result is the old [SCCN repo](https://github.com/sccn/xdf) and not the current one (tested in incognito mode). It would be nice if the actual GitHub repo showed up, but if you think the top result pointing to the PyPI site is OK that's fine with me too.

The repo name doesn't have to match the package name, but in this case it would solve the problem of getting the wrong repo as the second Google result. I don't think keeping all package names in the xdf-modules organization consistent is more important than that, so I'd have no problem with diverging here (there is already libxdf, which should be called xdf-c if everything was consistent).

@tstenner what do you think?

**Comment by tstenner** [comment]
For me, Google lists the super-repository as second hit and this repository somewhere on page 5.
Consistency with the other repositories in the organization is nice, but even after renaming the repo it would make it quite clear that it's the python package to read XDFs:

![2019-10-31-143117_658x121_scrot-fs8](https://user-images.githubusercontent.com/920936/67951123-31a08300-fbeb-11e9-8e52-016d3b7363c5.png)

I don't feel strongly about it, but I'd lean towards renaming the repo if there were a vote.

**Comment by cbrnr** [comment]
Yeah, same. I think it's more important that this repo shows up in the top results because it's the place where people can report issues and make PRs. I think renaming it to pyxdf will probably float it to the top, but we can't be 100% what will happen (although I guess it won't get worse).

Internal consistency is nice, but the C++ library is called libxdf and not xdf-c so the organization is already inconsistent - which means that renaming this to pyxdf shouldn't be a problem at all.

Anyone else want to comment? Otherwise, it's currently 2:1 for the name change.

**Comment by cboulay** [comment]
@chkothe @trmullen @arnodelorme

Maybe they don't care, but in the past they have cared very much about similar changes.

**Comment by tstenner** [comment]
> Otherwise, it's currently 2:1 for the name change.

Yeah, about that… I'm all in favor of democratic / meritocratic decisions, but I think we'd need a somewhat formalized decision making progress.

**Comment by cbrnr** [comment]
Please make a suggestion.

**Comment by tstenner** [comment]
The file format is a standard, so it's more or less untouchable, but everything else should have room for improvement and therefore should be changeable as long as someone has a convincing proposal (and does the work).

Apart from that, there's a lot to be decided. Who gets voting rights (e.g. everyone with at least X commits in the last year or Y created issues or is one of the SCCN folks)? How many votes are needed? Does anyone have veto rights (or are those even needed, as those who'd have a veto right would have enough standing to convince most others to vote against something)?

**Comment by tstenner** [comment]
> That's not true, the file format can also be extended/changed, but then it will need to be a different XDF version number: https://github.com/sccn/xdf/wiki/Specifications#introduction

But the additions would have to be standardized later, otherwise there's a base specification nobody's using.

> Let's not make things too complicated here.

Ok, I'll try to make it simple: anyone with commit access can vote for or against a proposal and make a decision after a reasonable time unless there's a strong vote or majority against it.

As an example:
- @cbrnr wants to rename the repository
- @cboulay is against it. I can't quite decipher if he's "somewhat against it" or "absolutely against it"
- @tstenner is somewhat in favor, but doesn't want to make the decision
- in case @cboulay's objection was only mildly against it, anyone could accept it

**Comment by cboulay** [comment]
I was only mildly against it... and now I'm for the name change. Initially my concern was that too many changes too quickly would be met with a strong reaction. I hope that now that enough time has passed since we moved things to different orgs and submodules (both XDF and LSL), and that this has proven to be a net benefit, there won't be a strong negative reaction to the repository name change. But let's make sure that we keep the redirect healthy by not making a different 'xdf-modules/xdf-python' repository in the future.

**Comment by trmullen** [comment]
Hi all,

If the proposal is to rename xdf-python to pyxdf, I am not opposed to that
(pyxdf is more succinct, and xdf is still clearly in the name).

But let's also have @chkothe weigh in on this since he wrote the original
code for pyxdf (with contributions from others on the intheon team).

all best,
Tim

PS: in future, maybe consider cc'ing via email individuals you wish to
reach directly as some people may not be using github issues as a messaging
service. I am not sure whether @arnodelorme has seen this. I have bcc'd
them here.

**Comment by chkothe** [comment]
Yeah as far as I'm concerned, renaming to that seems ok (does GitHub have
some forwarding after rename? I believe it does). The old name is in the
style of repos like liblsl-Python etc, but those naming conventions
predated having (now-entrenched) package names like pylsl etc. that blend
into the ecosystem of the respective language. (back then, I was just
focused on getting good language coverage in the first place).

Christian

**Comment by cbrnr** [comment]
Alright, it seems that we have reached a decision. Remember that this isn't that big of a change really, the user-facing name of the package has always been pyxdf. I'll go ahead and rename the repo today.

**Comment by cbrnr** [comment]
Don't forget to rename your forks if you want to go all-in on that change!

**Comment by cbrnr** [comment]
Updating the URL for `upstream`:

```
git remote set-url upstream git@github.com:xdf-modules/pyxdf.git
```

Setting it for `origin` (your fork) works analogously.
