### ISSUE TITLE
Single PC clock offset vs. latency and jitter

### ISSUE THREAD

**Issue by sunshineinsandiego** [xdf-modules/pyxdf#92]
Hi - My setup has a Cognionics headset and a heart rate monitor connected to the same PC via bluetooth, with both peripherals sending data to an LSL stream that is being recorded by the LabRecorder App on the same PC. Because this is a single PC setup, I am having trouble understanding the clock offset measurements that I'm seeing in my `xdf` file and how they relate to latency and jitter. 

My code to analyze this `xdf` file is in `python` so I make use of your `pyxdf` library, but I'm not sure how to interpret the data that I am seeing.

```
import pyxdf

# read raw data
in_file = 'baseline.xdf'

data, header = pyxdf.load_xdf(in_file)

# disaggregate streams
for stream in data:
    [stream_name] = stream['info']['name']
    [stream_type] = stream['info']['type']
    if (stream_type == 'ECG'):
        ecg_stream = stream
    elif (stream_type == 'EEG'):
        eeg_stream = stream
```

When I examine `ecg_stream`, I see a series of timestamps and clock offsets:
```
>>> eeg_stream['footer']['info']
{'first_timestamp': ['1386534.7123869'],
             'last_timestamp': ['1387116.712358'],
             'sample_count': ['291008'],
             'clock_offsets': [defaultdict(list,
                          {'offset': [defaultdict(list,
                                        {'time': ['1386540.36854905'],
                                         'value': ['-2.094986848533154e-05']}),
                            defaultdict(list,
                                        {'time': ['1386545.3686529'],
                                         'value': ['-1.600000541657209e-05']}),
                            defaultdict(list,
                                        {'time': ['1386550.3687949'],
                                         'value': ['-2.410006709396839e-05']}),
 ...
                            defaultdict(list,
                                        {'time': ['1386575.37059335'],
                                         'value': ['-2.505001612007618e-05']}),
...
```

I can also see a `time_series` of what I assume is the time at which each sample is received:
```
>>> eeg_stream['time_series']
array([[ 7.6612516e+04, -1.0331230e+03, -1.2857312e+05, ...,
         1.1788505e+06,  9.0000000e+00,  0.0000000e+00],
       [ 7.6611164e+04, -1.0314032e+03, -1.2857277e+05, ...,
         1.1788505e+06,  1.0000000e+01,  0.0000000e+00],...
```

After reading the [FAQs](https://labstreaminglayer.readthedocs.io/info/faqs.html) and the Time Synchronization [page](https://labstreaminglayer.readthedocs.io/info/time_synchronization.html) as well as looking through the `load_xdf` [function](https://github.com/xdf-modules/pyxdf/blob/main/pyxdf/pyxdf.py#L69). 

I still have the following questions.

- I have a series of timestamps in `'times_series'` for each peripheral. I assume that this is the local cpu clock time at which each sample is received without any corrections applied? Or are these corrected timestamps?
- For a single PC setup, what are the clock offset measurements actually measuring? They seem to be used [here](https://github.com/xdf-modules/pyxdf/blob/b3e19e0b05f18aae957509bb7f62dbd386f10fd3/pyxdf/pyxdf.py#L611) in `_clock_sync` but I'm not sure how they are being used to apply corrections (if any) to the raw time stamps.
- Dejittering seems to be done [here](https://github.com/xdf-modules/pyxdf/blob/b3e19e0b05f18aae957509bb7f62dbd386f10fd3/pyxdf/pyxdf.py#L645) by simply assuming a constant sampling rate for each uninterrupted segment (i.e. # of samples received / duration of samples).
- Is there any way to estimate uncorrected latency and jitter based on the data contained in this `xdf` file?
- How would I go about estimating the # of samples that were dropped / lost, if any?

Thanks!

**Comment by cboulay** [comment]
* eeg_stream["time_series"] contents are the actual data values. In your case, these are the EEG voltages.
* eeg_stream["time_stamps"] has the timestamp associated with each sample. Whether or not these were already corrected into a common base clock (i.e., that of the clock on which LabRecorder ran) depends on the `synchronize_clocks` argument when calling `load_xdf`. The default is True so by default they are corrected. If you are certain that every stream originated on the same computer and used the same clock then you can set this to False.
* The clock offsets are the differences in the timestamps of the recording computer and the stream outlet's computer after accounting for estimated transmission delay. To be honest, I'm not sure what happens when they are on the same computer, I would expect that the offsets should average out to 0.000. Any consistent non-zero value would indicate asynchrony in the time it takes to request the offset and the time it takes for the response. Maybe LSL should know when the 2 computers are the same and automatically return an offset of 0.0; that's worth looking into.
* LSL assumes that there are no samples dropped / lost. LSL itself does not lose samples unless there is a network interruption longer than 6 minutes (default). However, the device might lose samples between its acquisition and the call to LSL's `outlet.push_*`; if these are few and intermittent then LSL will simply interpret this as though the device has a slightly lower sample rate than it advertised. But see the documentation around the `jitter_break` parameters in load_xdf.
* I don't know what you mean by "latency" here.

**Comment by sunshineinsandiego** [comment]
Thanks Chad. Appreciate the reply, hopefully only a few quick follow-ups:
- To confirm, `'time_stamps'` is the timestamp associated with each sample as stamped by the LSL outlet computer (which in my case also happens to be the same recording computer). By default this is a corrected value and it is corrected for both synchronization (using clock offsets) and jitter (using a linear fit)
- When you say: "If you are certain every stream originated on the same computer", would having the EEG and HRM plugged into the same computer and running the outlets on the same computer on which LabRecorder is running qualify? No other computers seem be involved, yes?
- The stream outlet computer seems to be the recording computer when both the EEG and HRM are only plugged in to the recording computer, so yes, I agree, I'm not sure why there would be clock offsets. Unless it has something to do with the  time delay from the OS as mentioned [here](https://labstreaminglayer.readthedocs.io/info/faqs.html#timestamp-accuracy): "Aside from a delay, your time stamps will also have a jitter due to OS multi-tasking and buffering."
- When I say "latency", I mean delay between the time of acquisition of the sample by the peripheral and the timestamp that LSL gives it when it pushes it (which is what I see in `time_stamps`.

Thanks again for clarifying!

**Comment by cbrnr** [comment]
It does look like the two clocks, because they were recorded on the same computer, show only a very minimal difference (offset) of 24µs in your case. Do you think this is not accurate enough? I'm trying to find out if your question is about confirming your understanding, or if you are reporting an inconsistency (i.e. issue or bug).

**Comment by sunshineinsandiego** [comment]
I'm trying to understand what the two clocks are, if this is only a single computer? Shouldn't there only be 1 clock if I'm using 1 computer?

**Comment by cbrnr** [comment]
Yes, I think that's correct. Indeed you are seeing only a difference (an offset) of 24µs (in your output that you posted), which is negligible. So it is really just one clock. @cboulay @chkothe please correct me if I'm wrong.

**Comment by sunshineinsandiego** [comment]
So then what actually is that 24us measurement? Where is it coming from if this is not a RTT packet exchange between two clocks being measured?

**Comment by cboulay** [comment]
It's just 1 clock.

@sunshineinsandiego -- Clemens and I are assuming that you have a non-zero offset based on the values you're printing, but what's the average of all the offsets stored in your file?

If the average offset is significantly non-zero, then that implies the `request_time + RTT/2 != remote_time`. This can happy if there's some consistent asynchrony in the trip, i.e., longer to send the clock request than to receive the response (or vice versa?).

I'm sure we'd prefer if the calculated offset was exactly 0.0. This would probably require a more robust and complicated clock sync algorithm than we have currently, and I'm not sure if we can do it without changing the protocol. Another option would be to detect whenever the clocks are indeed the same and then bypass the clock sync check and just store 0.0. I'm sure this would be more complicated than it sounds -- what if there's a VM? What if in the future we replace std::chrono::steady_clock with another clock (still in seconds) that's more explicitly PTP-linked, but then someone is using LabRecorder with this new clock but one of their outlets is still using the old clock?
If someone can come up with an infallible method to verify the 2 clocks are indeed identical then this could be a feature added to liblsl.

**Comment by sunshineinsandiego** [comment]
Thanks. Here are the descriptive statistics of the offsets:
```
>>> offsets = [float(x['value'][0]) for x in eeg_stream['footer']['info']['clock_offsets'][0]['offset']]
>>> print(np.mean(offsets))
>>>  print(np.max(offsets))
>>> print(np.min(offsets))
>>> print(np.std(offsets))

-2.3713257784644764e-05
-8.200062438845634e-06
-6.140000186860561e-05
6.917753235303969e-06
```

So as you said, not significantly non-zero. 

Still, if `request_time + RTT/2 != remote_time` and there is no remote because  it's all on the same computer, where is the clock request being sent, and what is receiving the response? What are the two clocks in this case, if there is only one computer with only one local clock. Is one clock the lsl clock and the other clock the OS clock?

**Comment by cboulay** [comment]
They are both the same clock, but the clock is being queried independently by 2 separate processes: (1) LabRecorder and (2) the outlet application. If the clock was queried in both processes at the exact same time then you'd expect the processes to independently get the exact same value. Of course this is impossible, there's some processing time for LabRecorder to create the request, send it through the (albeit truncated localhost) TCP stack, for the outlet application to process the request, to poll the clock again, to form the response, and for the response to go through the TCP stack.

I'm going to close this issue because there's no actual issue here, unless there's a strong argument to be made that the 24 usec offset is a problem. Again, it isn't a problem for **your setup** because everything's on the same computer so you can simply choose to not apply clock synchronization during load_xdf.

**Comment by sunshineinsandiego** [comment]
Perfect, thanks Chad. Yes, no issue. Just trying to understand. Thanks for your help!
